---
kubernetes_cluster_name: kubernetes
kubernetes_pod_subnet: 192.168.0.0/16
kubernetes_service_subnet: 10.96.0.0/12
kubernetes_dns_domain: cluster.local
kubernetes_control_plane_endpoint: ""
kubernetes_apiserver_port: 6443
kubernetes_apiserver_cert_sans: []
kubernetes_cri_socket: unix:///run/containerd/containerd.sock
kubernetes_kubeadm_config_path: /etc/kubernetes/kubeadm-init.yaml
kubernetes_admin_user: "{{ ansible_user }}"
kubernetes_install_cni: true
kubernetes_cni_manifest_url: https://raw.githubusercontent.com/projectcalico/calico/v3.32.2/manifests/calico.yaml
kubernetes_wait_for_control_plane_timeout: 300

