---
- name: restart slurm daemon
  ansible.builtin.systemd:
    name: "{{ 'slurmctld' if slurm_common_node_role == 'controller' else 'slurmd' }}"
    state: restarted
    daemon_reload: true
  when: slurm_restart_services | bool

- name: restart munge
  ansible.builtin.systemd:
    name: munge
    state: restarted
  when: slurm_restart_services | bool

