---
- name: "관리자 사용자 정보 조회"
  ansible.builtin.getent:
    database: passwd
    key: "{{ kubernetes_admin_user }}"

- name: "관리자 kubeconfig 디렉토리 생성"
  ansible.builtin.file:
    path: "{{ getent_passwd[kubernetes_admin_user][4] }}/.kube"
    state: directory
    owner: "{{ kubernetes_admin_user }}"
    group: "{{ getent_passwd[kubernetes_admin_user][2] }}"
    mode: "0700"

- name: "관리자 kubeconfig 설치"
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ getent_passwd[kubernetes_admin_user][4] }}/.kube/config"
    remote_src: true
    owner: "{{ kubernetes_admin_user }}"
    group: "{{ getent_passwd[kubernetes_admin_user][2] }}"
    mode: "0600"

