---
application_role: "app"

docker_image: "fastapi-demo:1.0"
docker_container_name: "app-fastapi"

docker_ports:
  - "8000:8000"

docker_volumes: []

app_build_dir: "/opt/fastapi-app"

fastapi_python_image: "python:3.13-slim"
fastapi_port: 8000
fastapi_title: "Ansible FastAPI Example"
fastapi_message: "Nginx-FastAPI connection is working"
