- name: get vm info
  hosts: localhost
  gather_facts: false
  vars:
      gcp_project: test-project
      gcp_cred_kind: serviceaccount
      gcp_cred_file: "{{ playbook_dir }}/service-account.json"
      zone: "asia-northeast3-c"
      region: "asia-northeast3"

  tasks:
  - name: get_vm_resource_info
    gcp_compute_instance_info:
      zone: "{{ zone }}"
      filters:
      - name = gcp-ansible-test
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"

    register: res

  - debug: var=res.resources[0]
