- name: Create an instance
  hosts: localhost
  gather_facts: false
  vars_files: var_list.yaml

  tasks:
  - name: create a disk
    gcp_compute_disk:
        name: "{{ disk_name }}"
        size_gb: "{{ disk_size }}"
        source_image: "{{ disk_image }}"
        #source_snapshot:
         # selfLink: "{{ disk_snapshot }}"
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: "{{ disk_state }}"
        labels:
          user: wocheon07
    register: disk


  - name: create vm
    gcp_compute_instance:
      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: "{{ vm_state }}"
      name: "{{ vm_name }}"
      machine_type: "{{ machine_type }}"
      labels:
        user: wocheon07
      disks:
        - auto_delete: true
          boot: true
          source: "{{ disk }}"
      network_interfaces:
        - network:
            selfLink: "{{ network }}"
          subnetwork:
            selfLink: "{{ subnetwork }}"
          network_ip: "{{ vm_ip }}"
          access_configs:
            - name: External NAT
              type: ONE_TO_ONE_NAT
      scopes:
        - https://www.googleapis.com/auth/compute
    register: instance


#################################
#var_list.yml
#################################
#### gcp service-account file ###
gcp_cred_kind: serviceaccount
gcp_cred_file: ./service-account.json

### GCP Project & Regions ###
gcp_project: gcp-in-ca
region: "asia-northeast1"
zone: "asia-northeast1-a"

###disk###
disk_name : worker-05
disk_size : 20
disk_image: projects/gcp-in-ca/global/images/ansible-image
#disk_snapshot: projects/gcp-in-ca/global/snapshots/jenkins-snapshot-1
disk_state : present

###GCE_VM###
vm_state: present
vm_name : worker-05
machine_type : e2-micro

###GCE_VM_Network###
network : projects/gcp-in-ca/global/networks/test-vpc-1
subnetwork : projects/gcp-in-ca/regions/asia-northeast1/subnetworks/test-vpc-sub-03
vm_ip: 192.168.3.105
