---
gpu_install_driver: true
gpu_install_nvidia_container_toolkit: true
kubernetes_gpu_driver_managed: false

kubernetes_container_runtime: containerd
kubernetes_containerd_config_path: /etc/containerd/config.toml
kubernetes_set_nvidia_default_runtime: true
kubernetes_generate_containerd_config: true

gpu_verify_installation: true
gpu_verify_fail_on_error: true
