- name: Create an instance
  hosts: localhost
  gather_facts: false
  vars:
      gcp_project: gcp-in-ca
      gcp_cred_kind: serviceaccount
      gcp_cred_file: service-account.json
      zone: "asia-northeast1-a"
      region: "asia-northeast1"

  tasks:
  - name: create a disk
    gcp_compute_disk:
        name: 'ansible-disk-test'
        size_gb: 10
        source_snapshot:
          selfLink: "projects/gcp-in-ca/global/snapshots/gitlab-snapshot-1"
        #source_image: "projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20230817"
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
        labels:
          user: wocheon07
    register: disk


  - name: create vm
    gcp_compute_instance:
      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
      name: ansible-vm1
      machine_type: e2-micro
      labels:
        user: wocheon07
      disks:
        - auto_delete: true
          boot: true
          source: "{{ disk }}"
          #source:
           # selfLink: "projects/gcp-in-ca/zones/asia-northeast1-a/disks/ansible-disk-test"
      network_interfaces:
        - network:
            selfLink: "projects/gcp-in-ca/global/networks/test-vpc-1"
          subnetwork:
            selfLink: "projects/gcp-in-ca/regions/asia-northeast1/subnetworks/test-vpc-sub-03"
          access_configs:
            - name: External NAT
              type: ONE_TO_ONE_NAT
      scopes:
        - https://www.googleapis.com/auth/compute
    register: instance
[root@gcp-ansible-test g
